# Schema for the configuration files of the uc_lifepay module.
payment_method.settings.lifepay:
  type: mapping
  label: 'Lifepay form configuration settings'
  mapping:
    service_id:
      type: string
      label: 'Service ID'
    key:
      type: string
      label: 'Service key'
    skey:
      type: string
      label: 'Secret key'
    shop_hostname:
      type: string
      label: 'Order description with host name'
    api_version:
      type: string
      label: 'API version'
    payment_method:
      type: string
      label: 'Payment method'
    vat_products:
      type: string
      label: 'VAT for products'
    vat_delivery:
      type: string
      label: 'VAT for delivery'
    unit_products:
      type: string
      label: 'Units for products'
    unit_delivery:
      type: string
      label: 'Units for delivery'
    object_products:
      type: string
      label: 'Object for products'
    object_delivery:
      type: string
      label: 'Object for delivery'
    send_email:
      type: boolean
      label: 'Attach email in order'
    order_status_after_pay:
      type: string
      label: 'Order status after successfully payment'